/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Health check verifying app and database readiness.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Health check verifying app and database readiness.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Retrieve current authenticated user stats.
         */
        get: operations["get_current_user_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Profile
         * @description Retrieve full user profile with stats and recent activity.
         */
        get: operations["get_user_profile_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Retrieve user preferences.
         */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Settings
         * @description Update user preferences.
         */
        patch: operations["update_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Courses
         * @description List available courses.
         */
        get: operations["list_courses_api_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Course Path
         * @description Get hierarchical learning path (units -> skills -> lessons).
         */
        get: operations["get_course_path_api_courses__course_id__path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lesson Metadata
         * @description Get lesson exercises (payloads only, answer keys strictly omitted).
         */
        get: operations["get_lesson_metadata_api_lessons__lesson_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lesson_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Lesson Attempt
         * @description Authoritatively start a server-side lesson attempt.
         */
        post: operations["start_lesson_attempt_api_lessons__lesson_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attempt_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Attempt Answer
         * @description Validate submitted answer and enforce heart rules.
         */
        post: operations["check_attempt_answer_api_attempts__attempt_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attempt_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Attempt
         * @description Authoritatively complete an attempt, awarding XP and crowns.
         */
        post: operations["complete_attempt_api_attempts__attempt_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attempt_id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abandon Attempt
         * @description Abandon an active attempt.
         */
        post: operations["abandon_attempt_api_attempts__attempt_id__abandon_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hearts/refill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refill Hearts
         * @description Refill hearts via gems (350) or practice.
         */
        post: operations["refill_hearts_api_hearts_refill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leaderboard
         * @description Get current week's leaderboard standings.
         */
        get: operations["get_leaderboard_api_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Achievements
         * @description List achievements and progress.
         */
        get: operations["list_achievements_api_achievements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/advance-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Debug Advance Day
         * @description Simulate advancing logical clock.
         */
        post: operations["debug_advance_day_api_debug_advance_day_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/unlock-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Debug Unlock All
         * @description Debug helper: unlock all lessons for user 1.
         */
        post: operations["debug_unlock_all_api_debug_unlock_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/reset-demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Debug Reset Demo
         * @description Debug helper: reset user 1 progress and stats.
         */
        post: operations["debug_reset_demo_api_debug_reset_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbandonAttemptResponse */
        AbandonAttemptResponse: {
            /** Attempt Id */
            attempt_id: number;
            /** Status */
            status: string;
        };
        /** AchievementItem */
        AchievementItem: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Badge Icon */
            badge_icon: string;
            /** Target Value */
            target_value: number;
            /** Current Value */
            current_value: number;
            /** Is Unlocked */
            is_unlocked: boolean;
            /** Unlocked At */
            unlocked_at?: string | null;
        };
        /** ActivityItem */
        ActivityItem: {
            /** Activity Date */
            activity_date: string;
            /** Xp Earned */
            xp_earned: number;
            /** Lessons Completed */
            lessons_completed: number;
        };
        /** AdvanceDayRequest */
        AdvanceDayRequest: {
            /**
             * Days
             * @default 1
             */
            days: number;
        };
        /** AdvanceDayResponse */
        AdvanceDayResponse: {
            /** Date Offset Days */
            date_offset_days: number;
            /** Logical Now */
            logical_now: string;
        };
        /** CheckAnswerRequest */
        CheckAnswerRequest: {
            /** Exercise Id */
            exercise_id: number;
            /** User Answer */
            user_answer: unknown;
        };
        /** CheckAnswerResponse */
        CheckAnswerResponse: {
            /** Is Correct */
            is_correct: boolean;
            /** Correct Answer */
            correct_answer: unknown;
            /** Hearts Remaining */
            hearts_remaining: number;
            /** Attempt Status */
            attempt_status: string;
        };
        /** CompleteAttemptResponse */
        CompleteAttemptResponse: {
            /** Attempt Id */
            attempt_id: number;
            /** Status */
            status: string;
            /** Xp Earned */
            xp_earned: number;
            /** Accuracy */
            accuracy: number;
            /** Hearts Lost */
            hearts_lost: number;
            /** Is Replay */
            is_replay: boolean;
            /** New Crown Earned */
            new_crown_earned: boolean;
            /** Streak Current */
            streak_current: number;
        };
        /** CourseItem */
        CourseItem: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Flag Emoji */
            flag_emoji: string;
        };
        /** CoursePathResponse */
        CoursePathResponse: {
            /** Course Id */
            course_id: number;
            /** Title */
            title: string;
            /** Units */
            units: components["schemas"]["UnitSummary"][];
        };
        /** ExerciseClientView */
        ExerciseClientView: {
            /** Id */
            id: number;
            /** Exercise Order */
            exercise_order: number;
            /** Type */
            type: string;
            /** Payload */
            payload: Record<string, never>;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Timestamp */
            timestamp: string;
            /** Database */
            database: string;
            /** Version */
            version: string;
        };
        /** LeaderboardRanking */
        LeaderboardRanking: {
            /** Rank */
            rank: number;
            /** Username */
            username: string;
            /** Xp Earned */
            xp_earned: number;
            /** Is Current User */
            is_current_user: boolean;
        };
        /** LeaderboardResponse */
        LeaderboardResponse: {
            /** Week Start Date */
            week_start_date: string;
            /** Rankings */
            rankings: components["schemas"]["LeaderboardRanking"][];
        };
        /** LessonMetadataResponse */
        LessonMetadataResponse: {
            /** Id */
            id: number;
            /** Skill Id */
            skill_id: number;
            /** Title */
            title: string;
            /** Exercises */
            exercises: components["schemas"]["ExerciseClientView"][];
        };
        /** LessonSummary */
        LessonSummary: {
            /** Id */
            id: number;
            /** Lesson Order */
            lesson_order: number;
            /** Title */
            title: string;
            /** Is Completed */
            is_completed: boolean;
            /** Is Locked */
            is_locked: boolean;
        };
        /** ProfileResponse */
        ProfileResponse: {
            user: components["schemas"]["UserProfileStats"];
            /** Recent Activity */
            recent_activity: components["schemas"]["ActivityItem"][];
            /** Unlocked Achievements Count */
            unlocked_achievements_count: number;
        };
        /** RefillHeartsRequest */
        RefillHeartsRequest: {
            /**
             * Method
             * @enum {string}
             */
            method: "gems" | "practice";
        };
        /** RefillHeartsResponse */
        RefillHeartsResponse: {
            /** Hearts */
            hearts: number;
            /** Gems */
            gems: number;
            /** Hearts Updated At */
            hearts_updated_at: string;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Timezone */
            timezone: string;
            /** Date Offset Days */
            date_offset_days: number;
        };
        /** SettingsUpdateRequest */
        SettingsUpdateRequest: {
            /** Timezone */
            timezone?: string | null;
        };
        /** SimpleMessageResponse */
        SimpleMessageResponse: {
            /** Message */
            message: string;
        };
        /** SkillSummary */
        SkillSummary: {
            /** Id */
            id: number;
            /** Skill Order */
            skill_order: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Icon Name */
            icon_name: string;
            /** Total Crowns */
            total_crowns: number;
            /** Crowns Earned */
            crowns_earned: number;
            /** Lessons */
            lessons: components["schemas"]["LessonSummary"][];
        };
        /** StartAttemptResponse */
        StartAttemptResponse: {
            /** Attempt Id */
            attempt_id: number;
            /** Lesson Id */
            lesson_id: number;
            /** Status */
            status: string;
            /** Hearts Remaining */
            hearts_remaining: number;
            /** Exercises */
            exercises: components["schemas"]["ExerciseClientView"][];
        };
        /** UnitSummary */
        UnitSummary: {
            /** Id */
            id: number;
            /** Unit Order */
            unit_order: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Skills */
            skills: components["schemas"]["SkillSummary"][];
        };
        /** UserProfileStats */
        UserProfileStats: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Created At */
            created_at: string;
            /** Xp Total */
            xp_total: number;
            /** Streak Current */
            streak_current: number;
            /** Total Crowns */
            total_crowns: number;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Hearts */
            hearts: number;
            /**
             * Max Hearts
             * @default 5
             */
            max_hearts: number;
            /** Hearts Updated At */
            hearts_updated_at: string;
            /** Next Heart In Seconds */
            next_heart_in_seconds?: number | null;
            /** Xp Total */
            xp_total: number;
            /** Gems */
            gems: number;
            /** Streak Current */
            streak_current: number;
            /** Date Offset Days */
            date_offset_days: number;
            /** Timezone */
            timezone: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_current_user_api_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_api_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseItem"][];
                };
            };
        };
    };
    get_course_path_api_courses__course_id__path_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoursePathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_metadata_api_lessons__lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_lesson_attempt_api_lessons__lesson_id__start_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartAttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_attempt_answer_api_attempts__attempt_id__check_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_attempt_api_attempts__attempt_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteAttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abandon_attempt_api_attempts__attempt_id__abandon_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbandonAttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refill_hearts_api_hearts_refill_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefillHeartsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefillHeartsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_api_leaderboard_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_achievements_api_achievements_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_advance_day_api_debug_advance_day_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvanceDayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvanceDayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_unlock_all_api_debug_unlock_all_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_reset_demo_api_debug_reset_demo_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
