/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Health check verifying app and database readiness.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Health check verifying app and database readiness.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Retrieve current authenticated user state, hearts, streak, and daily progress.
         */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description Retrieve full user profile with stats and recent activity.
         */
        get: operations["get_profile_api_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Retrieve user preferences.
         */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Settings
         * @description Update user preferences.
         */
        patch: operations["update_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Courses
         * @description List all available courses.
         */
        get: operations["list_courses_api_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Course Path
         * @description Retrieve full hierarchical learning tree (units -> skills -> lessons)
         *     with user completion and locking.
         */
        get: operations["get_course_path_api_courses__course_id__path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lesson
         * @description Retrieve lesson metadata and public exercises. answer_json is NEVER included.
         */
        get: operations["get_lesson_api_lessons__lesson_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons/{lesson_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Lesson
         * @description Authoritatively initiate a lesson attempt.
         *
         *     Rules:
         *     - 409 OUT_OF_HEARTS if user has 0 hearts.
         *     - 403 LESSON_LOCKED if lesson is locked.
         *     - Abandons existing in_progress attempt if one exists.
         *     - Exercises delivered in deterministic exercise_order without answers.
         */
        post: operations["start_lesson_api_lessons__lesson_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attempt_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Answer
         * @description Authoritatively check a submitted exercise answer against server answer keys.
         */
        post: operations["check_answer_api_attempts__attempt_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attempt_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Attempt
         * @description Authoritatively complete an attempt, deriving accuracy and awarding XP.
         */
        post: operations["complete_attempt_api_attempts__attempt_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/{attempt_id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abandon Attempt
         * @description Abandon an active lesson attempt.
         */
        post: operations["abandon_attempt_api_attempts__attempt_id__abandon_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hearts/refill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refill Hearts
         * @description Refill hearts back to 5 via gems (350) or practice (free).
         */
        post: operations["refill_hearts_api_hearts_refill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leaderboard
         * @description Get current week's leaderboard standings.
         */
        get: operations["get_leaderboard_api_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Achievements
         * @description List achievements and user unlocking milestones.
         */
        get: operations["list_achievements_api_achievements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/advance-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance Day
         * @description Advance the user's logical clock by N days to simulate time progression.
         */
        post: operations["advance_day_api_debug_advance_day_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/unlock-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unlock All
         * @description Debug helper: unlock all lessons and skills for user 1.
         */
        post: operations["unlock_all_api_debug_unlock_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/reset-demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Demo
         * @description Debug helper: reset user 1 progress, hearts, gems, streak, and restore seed baseline.
         */
        post: operations["reset_demo_api_debug_reset_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbandonAttemptResponse */
        AbandonAttemptResponse: {
            /** Attempt Id */
            attempt_id: number;
            /** Status */
            status: string;
        };
        /** AchievementItem */
        AchievementItem: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Badge Icon */
            badge_icon: string;
            /** Target Value */
            target_value: number;
            /** Current Value */
            current_value: number;
            /** Is Unlocked */
            is_unlocked: boolean;
            /** Unlocked At */
            unlocked_at?: string | null;
        };
        /** ActivityItem */
        ActivityItem: {
            /** Activity Date */
            activity_date: string;
            /** Xp Earned */
            xp_earned: number;
            /** Lessons Completed */
            lessons_completed: number;
        };
        /** AdvanceDayRequest */
        AdvanceDayRequest: {
            /**
             * Days
             * @default 1
             */
            days: number;
        };
        /** AdvanceDayResponse */
        AdvanceDayResponse: {
            /** Date Offset Days */
            date_offset_days: number;
            /** Logical Now */
            logical_now: string;
        };
        /** CheckAnswerRequest */
        CheckAnswerRequest: {
            /** Exercise Id */
            exercise_id: number;
            /** User Answer */
            user_answer?: unknown | null;
            /** Answer */
            answer?: unknown | null;
        };
        /** CheckAnswerResponse */
        CheckAnswerResponse: {
            /** Is Correct */
            is_correct: boolean;
            /** Correct */
            correct?: boolean | null;
            /** Correct Answer */
            correct_answer: unknown;
            /** Hearts Remaining */
            hearts_remaining: number;
            /** Hearts */
            hearts?: number | null;
            /** Attempt Status */
            attempt_status: string;
            /**
             * Lesson Failed
             * @default false
             */
            lesson_failed: boolean | null;
            /** Explanation */
            explanation?: string | null;
        };
        /** CompleteAttemptResponse */
        CompleteAttemptResponse: {
            /** Attempt Id */
            attempt_id: number;
            /** Status */
            status: string;
            /** Xp Earned */
            xp_earned: number;
            /** Accuracy */
            accuracy: number;
            /** Hearts Lost */
            hearts_lost: number;
            /** Is Replay */
            is_replay: boolean;
            /** New Crown Earned */
            new_crown_earned: boolean;
            /** Streak Current */
            streak_current: number;
            /** Time Spent Seconds */
            time_spent_seconds?: number | null;
            /** Crowns After */
            crowns_after?: number | null;
            /** Skill Completed */
            skill_completed?: boolean | null;
            /** Unit Completed */
            unit_completed?: boolean | null;
            /** New Achievements */
            new_achievements?: string[] | null;
            /** Streak Extended */
            streak_extended?: boolean | null;
        };
        /** CourseItem */
        CourseItem: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Flag Emoji */
            flag_emoji: string;
        };
        /** CoursePathResponse */
        CoursePathResponse: {
            /** Course Id */
            course_id: number;
            /** Title */
            title: string;
            /** Units */
            units: components["schemas"]["UnitSummary"][];
        };
        /** ExerciseClientView */
        ExerciseClientView: {
            /** Id */
            id: number;
            /** Exercise Order */
            exercise_order: number;
            /** Type */
            type: string;
            /** Payload */
            payload: Record<string, never>;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Timestamp */
            timestamp: string;
            /** Database */
            database: string;
            /** Version */
            version: string;
        };
        /** LeaderboardRanking */
        LeaderboardRanking: {
            /** Rank */
            rank: number;
            /** Username */
            username: string;
            /** Xp Earned */
            xp_earned: number;
            /** Is Current User */
            is_current_user: boolean;
        };
        /** LeaderboardResponse */
        LeaderboardResponse: {
            /** Week Start Date */
            week_start_date: string;
            /** Rankings */
            rankings: components["schemas"]["LeaderboardRanking"][];
        };
        /** LessonMetadataResponse */
        LessonMetadataResponse: {
            /** Id */
            id: number;
            /** Skill Id */
            skill_id: number;
            /** Title */
            title: string;
            /** Exercises */
            exercises: components["schemas"]["ExerciseClientView"][];
        };
        /** LessonSummary */
        LessonSummary: {
            /** Id */
            id: number;
            /** Lesson Order */
            lesson_order: number;
            /** Title */
            title: string;
            /** Is Completed */
            is_completed: boolean;
            /** Is Locked */
            is_locked: boolean;
        };
        /** ProfileResponse */
        ProfileResponse: {
            user: components["schemas"]["UserProfileStats"];
            /** Recent Activity */
            recent_activity: components["schemas"]["ActivityItem"][];
            /** Unlocked Achievements Count */
            unlocked_achievements_count: number;
        };
        /** RefillHeartsRequest */
        RefillHeartsRequest: {
            /**
             * Method
             * @enum {string}
             */
            method: "gems" | "practice";
        };
        /** RefillHeartsResponse */
        RefillHeartsResponse: {
            /** Hearts */
            hearts: number;
            /** Gems */
            gems: number;
            /** Hearts Updated At */
            hearts_updated_at: string;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Timezone */
            timezone: string;
            /** Date Offset Days */
            date_offset_days: number;
        };
        /** SettingsUpdateRequest */
        SettingsUpdateRequest: {
            /** Timezone */
            timezone?: string | null;
        };
        /** SimpleMessageResponse */
        SimpleMessageResponse: {
            /** Message */
            message: string;
        };
        /** SkillSummary */
        SkillSummary: {
            /** Id */
            id: number;
            /** Skill Order */
            skill_order: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Icon Name */
            icon_name: string;
            /** Total Crowns */
            total_crowns: number;
            /** Crowns Earned */
            crowns_earned: number;
            /** Lessons */
            lessons: components["schemas"]["LessonSummary"][];
        };
        /** StartAttemptResponse */
        StartAttemptResponse: {
            /** Attempt Id */
            attempt_id: number;
            /** Lesson Id */
            lesson_id: number;
            /** Status */
            status: string;
            /** Hearts Remaining */
            hearts_remaining: number;
            /** Exercises */
            exercises: components["schemas"]["ExerciseClientView"][];
        };
        /** UnitSummary */
        UnitSummary: {
            /** Id */
            id: number;
            /** Unit Order */
            unit_order: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Skills */
            skills: components["schemas"]["SkillSummary"][];
        };
        /** UserProfileStats */
        UserProfileStats: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Created At */
            created_at: string;
            /** Xp Total */
            xp_total: number;
            /** Streak Current */
            streak_current: number;
            /** Total Crowns */
            total_crowns: number;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Hearts */
            hearts: number;
            /**
             * Max Hearts
             * @default 5
             */
            max_hearts: number;
            /** Hearts Updated At */
            hearts_updated_at: string;
            /** Next Heart In Seconds */
            next_heart_in_seconds?: number | null;
            /** Next Heart At */
            next_heart_at?: string | null;
            /** Xp Total */
            xp_total: number;
            /** Gems */
            gems: number;
            /** Streak Current */
            streak_current: number;
            /**
             * Streak Active Today
             * @default false
             */
            streak_active_today: boolean | null;
            /**
             * Daily Xp Goal
             * @default 20
             */
            daily_xp_goal: number | null;
            /**
             * Daily Xp Progress
             * @default 0
             */
            daily_xp_progress: number | null;
            /** Date Offset Days */
            date_offset_days: number;
            /** Timezone */
            timezone: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_api_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseItem"][];
                };
            };
        };
    };
    get_course_path_api_courses__course_id__path_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoursePathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_api_lessons__lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonMetadataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_lesson_api_lessons__lesson_id__start_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartAttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_answer_api_attempts__attempt_id__check_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_attempt_api_attempts__attempt_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteAttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abandon_attempt_api_attempts__attempt_id__abandon_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path: {
                attempt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbandonAttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refill_hearts_api_hearts_refill_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefillHeartsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefillHeartsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_api_leaderboard_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_achievements_api_achievements_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_day_api_debug_advance_day_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvanceDayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvanceDayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlock_all_api_debug_unlock_all_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_demo_api_debug_reset_demo_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: number;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimpleMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
